**Import the neccesary packeges.**

In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import math
import numpy as np
import seaborn as sns
from currency_converter import CurrencyConverter
from datetime import date

**Upload the 174 index data.**

In [4]:
df_49=pd.read_csv("/Users/a/Dropbox/Thesis/Thesis/Coding/186IndexesData+Cleaning/NEWERDataIndexes/49_Industry_Portfolios_Daily.csv", index_col=0)
df_25_Asia=pd.read_csv("/Users/a/Dropbox/Thesis/Thesis/Coding/186IndexesData+Cleaning/NEWERDataIndexes/Asia_Pacific_ex_Japan_25_Portfolios_ME_OP_Daily.csv", index_col=0)
df_25_Global=pd.read_csv("/Users/a/Dropbox/Thesis/Thesis/Coding/186IndexesData+Cleaning/NEWERDataIndexes/Developed_25_Portfolios_ME_OP_Daily.csv", index_col=0)
df_25_Eur=pd.read_csv("/Users/a/Dropbox/Thesis/Thesis/Coding/186IndexesData+Cleaning/NEWERDataIndexes/Europe_25_Portfolios_ME_OP_Daily.csv", index_col=0)
df_25_Jap=pd.read_csv("/Users/a/Dropbox/Thesis/Thesis/Coding/186IndexesData+Cleaning/NEWERDataIndexes/Japan_25_Portfolios_ME_OP_Daily.csv", index_col=0)
df_25_NortAM=pd.read_csv("/Users/a/Dropbox/Thesis/Thesis/Coding/186IndexesData+Cleaning/NEWERDataIndexes/North_America_25_Portfolios_ME_OP_Daily.csv", index_col=0)

**The columns for the 25 developed portfolios have the same name for the different regions.**

In [5]:
df_25_Asia

,SMALL LoBO,ME1 BO2,ME1 BO3,ME1 BO4,SMALL HiBO,ME2 BO1,ME2 BO2,ME2 BO3,ME2 BO4,ME2 BO5,...,ME4 BO1,ME4 BO2,ME4 BO3,ME4 BO4,ME4 BO5,BIG LoBO,ME5 BO2,ME5 BO3,ME5 BO4,BIG HiBO
,,,,,,,,,,,,,,,,,,,,,
19900702,1.33,0.03,0.11,1.55,0.30,1.19,0.11,-0.45,-0.37,0.44,...,-0.07,-0.10,0.41,0.86,1.24,0.31,1.39,0.25,0.32,0.18
19900703,0.28,0.14,0.33,1.08,0.94,1.77,-0.26,1.35,-0.60,0.11,...,-0.37,0.87,0.99,0.13,1.19,1.27,1.17,1.02,1.04,1.13
19900704,1.24,2.07,1.28,0.88,1.86,1.24,0.65,0.83,-0.55,1.29,...,0.78,0.94,1.18,1.15,1.33,1.07,0.67,1.44,2.43,1.15
19900705,-0.61,-0.31,-0.60,-0.56,-0.35,-0.04,-0.72,0.69,-1.43,-0.52,...,-0.23,-0.01,-0.26,-0.93,-0.79,-0.20,-0.26,0.70,0.66,0.55
19900706,-0.74,-0.76,-0.09,-0.40,-0.14,-0.58,-0.59,0.50,1.18,0.12,...,0.35,-0.58,0.55,0.20,0.30,-0.45,0.01,-0.24,-0.10,0.07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20200325,1.27,2.68,1.35,1.64,0.81,1.78,2.86,1.68,1.62,4.09,...,3.37,5.21,5.64,3.94,3.13,3.91,5.16,6.53,4.76,4.00
20200326,2.02,0.44,0.38,1.97,1.28,1.31,2.08,2.41,2.25,3.32,...,2.03,6.64,3.76,3.00,4.27,0.65,0.79,1.17,1.31,3.33
20200327,0.60,1.28,0.97,0.36,1.59,0.63,1.40,0.89,1.60,0.43,...,1.14,-0.34,0.53,-0.17,-0.30,0.53,0.98,-1.64,-1.69,-2.92
20200330,0.37,-0.39,-3.67,-0.92,-0.22,-0.62,-0.78,0.70,-0.79,0.49,...,0.10,1.93,-0.31,0.48,3.20,-2.23,-1.52,2.32,2.01,4.98
20200331,1.54,1.34,0.48,1.33,2.40,1.18,1.95,2.80,3.99,2.86,...,0.68,-0.21,0.01,0.91,-0.60,3.09,2.64,0.48,-0.76,-3.20

In [6]:
df_25_Global

,SMALL LoBO,ME1 BO2,ME1 BO3,ME1 BO4,SMALL HiBO,ME2 BO1,ME2 BO2,ME2 BO3,ME2 BO4,ME2 BO5,...,ME4 BO1,ME4 BO2,ME4 BO3,ME4 BO4,ME4 BO5,BIG LoBO,ME5 BO2,ME5 BO3,ME5 BO4,BIG HiBO
,,,,,,,,,,,,,,,,,,,,,
19900702,0.27,0.35,0.63,0.70,0.81,0.48,0.57,0.69,0.69,0.78,...,0.53,0.44,0.61,0.64,0.69,0.79,0.72,0.92,0.80,0.68
19900703,0.15,0.15,0.35,0.19,0.33,0.15,0.41,0.25,0.43,0.52,...,0.38,0.38,0.26,0.34,0.43,0.28,0.33,0.07,0.14,0.20
19900704,0.25,0.12,0.28,0.36,0.29,0.58,0.41,0.61,0.48,0.58,...,0.80,0.83,0.58,0.60,0.63,0.86,0.82,0.70,0.46,0.69
19900705,-0.50,-0.39,-0.22,-0.58,-0.30,-0.49,-0.37,-0.38,-0.53,-0.50,...,-0.42,-0.39,-0.62,-0.54,-0.29,-0.53,-0.74,-0.87,-0.82,-0.94
19900706,-0.17,-0.04,0.03,0.07,0.08,0.03,0.03,0.24,0.08,0.12,...,0.14,0.21,0.15,0.02,0.22,-0.13,0.19,0.17,0.37,0.27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20200325,2.93,3.32,3.52,3.92,5.08,2.93,3.70,3.84,3.80,4.45,...,2.98,4.85,4.56,4.37,3.94,3.14,3.74,3.61,1.75,1.58
20200326,3.14,3.04,2.67,1.93,1.16,3.76,3.87,3.87,3.34,2.21,...,4.35,3.40,4.19,3.62,4.17,3.48,4.73,4.36,4.80,5.16
20200327,0.55,1.34,0.46,1.21,1.63,-0.39,-0.11,-0.75,-0.05,0.46,...,-1.01,-0.34,-1.52,-0.96,-1.43,-1.96,-2.21,-2.62,-2.30,-2.83
20200330,0.04,-0.19,-0.60,-0.50,-0.75,0.77,0.32,0.38,-0.12,-0.16,...,0.37,0.69,0.89,0.96,1.57,1.00,0.98,2.38,2.47,3.04
20200331,0.56,0.49,0.90,1.42,1.70,-0.41,0.70,0.88,0.70,0.94,...,-0.87,-0.50,-0.32,-0.37,-0.69,-0.37,-0.18,-0.43,-0.95,-1.09

**Lets rename the columns with the name of their region in front of the name.**

Asia

In [7]:
column_names = []

for i in range(len(df_25_Asia.columns)):
    column_names.append("Asia"+df_25_Asia.columns[i])

In [8]:
df_25_Asia.columns=column_names

Global

In [9]:
column_names = []

for i in range(len(df_25_Global.columns)):
    column_names.append("Global"+df_25_Global.columns[i])

In [10]:
df_25_Global.columns=column_names

Europe

In [11]:
column_names = []

for i in range(len(df_25_Eur.columns)):
    column_names.append("Europe"+df_25_Eur.columns[i])

In [12]:
df_25_Eur.columns=column_names

Japan

In [13]:
column_names = []

for i in range(len(df_25_Jap.columns)):
    column_names.append("Japan"+df_25_Jap.columns[i])

In [14]:
df_25_Jap.columns=column_names

North America

In [15]:
column_names = []

for i in range(len(df_25_NortAM.columns)):
    column_names.append("NAmerica"+df_25_NortAM.columns[i])

In [16]:
df_25_NortAM.columns=column_names

**Now we join the dataframes together.**

Begin by joining the 5 - 25 portfolio dataframes.

In [17]:
df_125 = df_25_Asia.join(df_25_Global).join(df_25_Eur).join(df_25_Jap).join(df_25_NortAM)

In [18]:
df_125.head()

,AsiaSMALL LoBO,AsiaME1 BO2,AsiaME1 BO3,AsiaME1 BO4,AsiaSMALL HiBO,AsiaME2 BO1,AsiaME2 BO2,AsiaME2 BO3,AsiaME2 BO4,AsiaME2 BO5,...,NAmericaME4 BO1,NAmericaME4 BO2,NAmericaME4 BO3,NAmericaME4 BO4,NAmericaME4 BO5,NAmericaBIG LoBO,NAmericaME5 BO2,NAmericaME5 BO3,NAmericaME5 BO4,NAmericaBIG HiBO
,,,,,,,,,,,,,,,,,,,,,
19900702,1.33,0.03,0.11,1.55,0.30,1.19,0.11,-0.45,-0.37,0.44,...,0.12,-0.26,0.29,-0.15,0.09,0.24,0.23,0.77,0.29,0.49
19900703,0.28,0.14,0.33,1.08,0.94,1.77,-0.26,1.35,-0.60,0.11,...,-0.14,-0.03,0.15,-0.08,0.07,0.01,0.25,0.01,0.15,0.41
19900704,1.24,2.07,1.28,0.88,1.86,1.24,0.65,0.83,-0.55,1.29,...,-0.07,0.03,0.05,0.02,-0.04,0.06,0.06,0.01,0.03,0.00
19900705,-0.61,-0.31,-0.60,-0.56,-0.35,-0.04,-0.72,0.69,-1.43,-0.52,...,-0.85,-0.94,-0.89,-0.76,-0.25,-1.00,-0.95,-1.08,-0.99,-1.30
19900706,-0.74,-0.76,-0.09,-0.40,-0.14,-0.58,-0.59,0.50,1.18,0.12,...,0.53,0.17,0.64,0.57,0.51,-0.01,0.61,0.51,0.70,1.07

Now we add the 49 portfolios dataframe to the df_125, it has data since 1926 which we don't need

In [19]:
df_174=df_125.join(df_49)

df_174

,AsiaSMALL LoBO,AsiaME1 BO2,AsiaME1 BO3,AsiaME1 BO4,AsiaSMALL HiBO,AsiaME2 BO1,AsiaME2 BO2,AsiaME2 BO3,AsiaME2 BO4,AsiaME2 BO5,...,Boxes,Trans,Whlsl,Rtail,Meals,Banks,Insur,RlEst,Fin,Other
19900702,1.33,0.03,0.11,1.55,0.30,1.19,0.11,-0.45,-0.37,0.44,...,-0.68,-0.16,0.35,0.39,0.32,-0.01,0.25,-0.54,-0.09,1.04
19900703,0.28,0.14,0.33,1.08,0.94,1.77,-0.26,1.35,-0.60,0.11,...,0.42,-0.02,-0.09,0.29,0.40,-0.25,-0.14,0.30,0.08,1.53
19900704,1.24,2.07,1.28,0.88,1.86,1.24,0.65,0.83,-0.55,1.29,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19900705,-0.61,-0.31,-0.60,-0.56,-0.35,-0.04,-0.72,0.69,-1.43,-0.52,...,-0.14,-1.09,-0.86,-0.96,-1.29,-1.30,-1.06,0.06,-0.63,-0.81
19900706,-0.74,-0.76,-0.09,-0.40,-0.14,-0.58,-0.59,0.50,1.18,0.12,...,1.32,0.56,0.27,0.54,0.72,0.42,0.69,0.67,0.16,0.82
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20200325,1.27,2.68,1.35,1.64,0.81,1.78,2.86,1.68,1.62,4.09,...,-0.74,2.76,1.84,-1.79,1.91,3.42,5.13,5.81,4.18,2.71
20200326,2.02,0.44,0.38,1.97,1.28,1.31,2.08,2.41,2.25,3.32,...,8.57,4.88,7.81,3.99,3.07,6.61,7.35,11.27,7.22,3.69
20200327,0.60,1.28,0.97,0.36,1.59,0.63,1.40,0.89,1.60,0.43,...,-0.43,-4.20,-4.44,-2.23,-4.27,-4.67,-3.40,-4.58,-3.18,-3.08
20200330,0.37,-0.39,-3.67,-0.92,-0.22,-0.62,-0.78,0.70,-0.79,0.49,...,3.98,0.83,3.04,2.97,1.47,1.46,4.15,1.54,2.77,1.81
20200331,1.54,1.34,0.48,1.33,2.40,1.18,1.95,2.80,3.99,2.86,...,-1.88,-0.87,-1.22,-1.41,-1.77,-3.37,-2.27,-5.16,-2.64,-0.15

Now we have all the indexes together in a dataframe.

**Change the index from object to datetime.**

In [20]:
df_174.index.dtype

dtype('int64')

In [21]:
df_174.index=pd.to_datetime(df_174.index.astype(str), format = "%Y%m%d")

**Now we want to calculate cumulative returns on weekly basis, from Wednesdays to Wednesdays.**

Begin by adding two zeros in front of each return so they are in \%.

In [22]:
df_174 = df_174*0.01

Calculate the cumulative returns

In [23]:
df_174_weekly = df_174.resample("W-WED").agg(lambda x: (x+1).prod()-1)

In [24]:
df_174_weekly.tail(50)

,AsiaSMALL LoBO,AsiaME1 BO2,AsiaME1 BO3,AsiaME1 BO4,AsiaSMALL HiBO,AsiaME2 BO1,AsiaME2 BO2,AsiaME2 BO3,AsiaME2 BO4,AsiaME2 BO5,...,Boxes,Trans,Whlsl,Rtail,Meals,Banks,Insur,RlEst,Fin,Other
2019-04-24,-0.011974,-0.016314,-0.013260,0.000043,-0.011963,-0.005897,-0.010868,-0.010870,-0.020809,-0.013261,...,0.030283,0.015866,0.009128,0.008754,0.019490,0.001270,0.023238,0.014673,-0.003929,0.009749
2019-05-01,-0.009902,0.005983,0.004772,-0.001946,-0.013240,0.013750,0.002699,-0.000507,-0.005398,0.011116,...,0.003077,-0.028594,-0.011474,-0.011615,-0.000429,0.012322,0.014215,-0.003015,0.002915,0.025663
2019-05-08,-0.020187,-0.025336,-0.020676,-0.026359,-0.026793,-0.025069,-0.022989,-0.024465,-0.018658,-0.016019,...,0.016194,-0.011566,0.013333,-0.006441,0.006910,-0.014119,0.009424,-0.051628,-0.009759,-0.021625
2019-05-15,-0.002976,-0.006297,-0.006901,-0.019077,-0.012833,-0.028536,-0.009833,-0.012539,-0.000565,-0.012768,...,0.003524,-0.013671,-0.019761,-0.021602,-0.003200,-0.020574,0.000250,-0.031636,-0.022770,-0.016207
2019-05-22,-0.003316,-0.010276,0.001081,-0.015423,-0.000054,0.001591,-0.011060,-0.017163,0.009266,-0.006158,...,-0.029107,-0.010846,0.006585,-0.001721,-0.003403,0.009910,0.029391,-0.015366,0.004832,-0.004056
2019-05-29,-0.002821,-0.002933,-0.006852,0.000595,-0.005118,-0.001533,-0.006504,-0.003440,-0.001455,0.019336,...,-0.024470,-0.033698,-0.025426,-0.021905,-0.027739,-0.018308,-0.019114,-0.016044,-0.016847,-0.024289
2019-06-05,-0.007090,-0.006418,-0.005916,-0.012080,-0.003808,-0.007459,0.000090,-0.017182,-0.019059,-0.014968,...,0.050423,0.030197,0.014196,-0.000031,0.038847,0.012106,0.022869,0.004600,0.024709,0.029081
2019-06-12,-0.001250,0.007294,-0.000128,-0.000520,-0.010215,0.000385,0.003967,0.007286,0.017866,0.008318,...,0.021896,0.007342,0.020191,0.040311,0.026540,0.007537,0.002965,0.025701,0.002094,0.010721
2019-06-19,-0.004014,0.001762,0.007784,-0.004441,-0.002978,0.004566,-0.000326,0.012966,0.031087,0.000887,...,-0.003193,0.000983,0.001748,0.024011,0.008174,0.002390,0.017189,0.032597,0.003360,0.010733
2019-06-26,0.009178,-0.012236,0.006092,0.008202,0.007491,0.004294,-0.003545,-0.009678,-0.008786,0.002644,...,-0.012480,-0.013520,-0.007427,-0.007461,-0.002350,-0.004257,-0.022004,-0.020656,-0.007369,0.000605
2019-07-03,0.016596,0.017598,0.018704,0.011035,0.006395,0.021628,0.013956,0.015492,0.016154,0.030004,...,0.072327,0.029298,0.031714,0.023189,0.036151,0.039286,0.036598,0.051711,0.038957,0.029184
2019-07-10,-0.006425,-0.009597,-0.005202,-0.007642,-0.001221,-0.001262,-0.012273,0.001162,-0.006346,0.005978,...,-0.020859,-0.014628,-0.012468,0.018117,0.000480,-0.000662,0.000490,-0.011483,-0.001618,-0.012051
2019-07-17,0.005996,0.001098,0.009128,0.010133,0.009599,0.001079,0.005698,0.003347,0.002674,0.008583,...,-0.025708,0.000820,-0.007002,0.005831,0.003685,-0.003588,0.020692,0.003341,0.009288,-0.023434
2019-07-24,0.012712,0.003998,-0.003518,-0.003915,0.009965,-0.000513,-0.002919,0.002874,-0.007516,0.020827,...,0.042393,0.035301,0.016148,-0.001946,0.000719,0.038173,-0.013276,0.018651,0.019711,0.010759
2019-07-31,-0.009868,-0.021417,-0.016595,-0.017458,-0.013049,-0.010575,-0.019481,-0.012735,-0.007192,-0.020451,...,-0.011980,-0.004942,-0.002306,-0.035323,0.004818,-0.010015,-0.007267,0.011433,-0.021324,-0.008471
2019-08-07,-0.034761,-0.040311,-0.044212,-0.040622,-0.032663,-0.048713,-0.038643,-0.039102,-0.042553,-0.049271,...,0.000071,-0.050311,-0.037260,-0.029903,0.000508,-0.057942,-0.025309,-0.055920,-0.048467,-0.037322
2019-08-14,-0.001894,-0.005342,-0.007210,-0.006660,-0.008452,-0.011254,-0.008021,0.005670,-0.014754,0.019608,...,-0.014562,-0.039441,-0.007676,-0.022236,-0.006835,-0.028232,-0.019070,-0.029395,-0.030409,-0.014791
2019-08-21,-0.000646,0.010992,0.002883,0.004568,0.010381,-0.001096,0.003282,0.001430,0.013205,-0.017281,...,0.025747,0.024924,0.027069,0.050477,0.020630,0.027178,0.009542,0.064083,0.029859,0.007160
2019-08-28,-0.006125,-0.011098,-0.011877,0.000507,-0.007998,-0.005486,-0.003945,-0.017213,-0.012806,0.003339,...,-0.010440,-0.028029,-0.022118,-0.007607,-0.003611,-0.011022,-0.032197,-0.037260,-0.005229,-0.004796
2019-09-04,0.008003,0.013453,0.015653,0.013134,0.009350,0.004917,0.014854,0.023508,0.034037,0.011039,...,0.016748,0.016060,0.022149,0.017886,0.005116,0.018443,0.015603,0.028510,0.021814,0.024372
2019-09-11,0.008501,0.018203,0.010220,0.013863,0.014146,0.011911,0.018413,0.017397,0.009419,0.028290,...,-0.005633,0.052290,0.058746,0.024528,-0.016386,0.043598,0.019230,0.070131,0.032075,0.027361
2019-09-18,0.008113,0.006269,0.015062,0.004086,0.013015,0.010609,0.000082,0.012746,0.001364,0.012211,...,-0.001184,-0.007847,-0.001802,-0.007007,-0.000347,0.011989,0.006086,-0.022919,0.017382,-0.001075
2019-09-25,-0.005427,-0.019996,-0.002924,-0.013396,-0.017898,-0.013943,-0.009581,-0.010998,-0.011608,-0.014569,...,-0.004860,-0.023662,-0.004961,-0.012162,-0.010747,-0.008813,-0.011485,-0.011904,-0.016489,-0.012016
2019-10-02,-0.007792,-0.004435,-0.003105,0.001822,0.002674,-0.004407,-0.006094,-0.003010,-0.009391,-0.009890,...,-0.037236,-0.053686,-0.031292,-0.023912,-0.032325,-0.040602,-0.036083,-0.052757,-0.069105,-0.028027
2019-10-09,-0.007188,-0.007583,-0.001715,-0.008979,-0.010476,-0.016216,0.011474,-0.005995,0.006708,-0.001625,...,0.010126,0.003013,-0.001705,0.011003,0.013238,0.006485,0.006242,0.009607,0.007855,0.007312
2019-10-16,0.008198,0.009427,0.004378,0.016453,0.011985,0.006295,-0.002103,0.003085,0.012341,0.011282,...,0.022891,0.049164,0.042389,0.030089,-0.002034,0.041132,0.032946,0.045703,0.033027,0.017667
2019-10-23,0.001683,0.007374,0.004376,0.000599,0.017894,-0.001911,0.015249,0.003277,0.002979,0.009124,...,0.024995,0.024403,0.016394,-0.002379,-0.023201,0.015979,0.017086,0.013059,0.017539,0.011722
2019-10-30,-0.003008,0.017085,0.001093,0.021060,0.015587,0.001591,0.000098,0.008305,0.021784,0.007000,...,0.016232,0.003096,0.003133,0.005603,0.003275,0.018178,0.013072,0.019279,0.017792,0.022533
2019-11-06,0.000494,0.018301,0.007216,0.015437,0.004373,0.006407,0.007707,0.012638,0.017283,0.024169,...,-0.018368,0.016293,0.025119,0.012000,-0.003938,0.019473,0.007074,0.015469,0.018626,0.036574
2019-11-13,-0.014131,0.003627,0.007716,-0.014166,0.002814,-0.012954,0.005561,-0.010970,-0.009092,-0.030036,...,0.000023,-0.019071,0.008114,-0.005893,0.003375,0.001630,0.014111,0.016501,0.004681,-0.001618
2019-11-20,-0.007221,0.009513,-0.004754,-0.017013,-0.008450,-0.003425,-0.020041,0.005378,0.003195,0.019196,...,0.003668,-0.010825,-0.000559,-0.005859,0.001291,0.004977,0.027281,0.018655,0.016991,-0.002234
2019-11-27,-0.013944,-0.016772,-0.013432,-0.017620,0.008243,-0.004950,-0.006686,-0.006735,0.007790,-0.011318,...,0.012564,0.027843,0.013205,0.020629,0.029103,0.017887,0.013537,0.023921,0.024246,0.008904
2019-12-04,-0.006293,0.003867,0.010706,-0.004904,-0.003430,-0.012352,0.009325,-0.010565,0.001458,-0.002363,...,-0.011849,-0.030946,-0.008237,-0.021750,-0.009602,-0.012754,-0.016593,-0.007266,-0.011945,-0.014251
2019-12-11,-0.003338,0.006765,-0.005195,0.008160,0.009285,-0.000330,0.003195,0.014422,0.002675,0.003765,...,-0.006074,0.009179,0.012405,0.001247,0.010590,0.013096,0.004469,0.014276,0.007356,0.015309
2019-12-18,0.010429,0.013327,0.014931,0.015663,0.003586,0.008449,0.016705,0.019404,0.016707,0.020447,...,0.012392,0.013856,0.003171,0.012612,0.013421,0.025871,0.025578,0.017473,0.008406,0.006890
2019-12-25,0.007011,0.011439,0.012449,-0.001600,0.012518,0.004907,0.012523,0.015248,0.012655,0.013453,...,0.010517,0.008504,0.011105,0.003789,0.006295,0.001498,0.002991,0.008358,0.003290,0.007909
2020-01-01,0.022684,0.016786,0.008719,0.020932,0.015974,0.024894,0.013439,0.011224,0.015865,0.015564,...,-0.002706,-0.006442,-0.000906,0.010296,0.000579,0.002568,0.001995,0.006192,-0.001229,0.001987
2020-01-08,-0.009328,-0.024287,-0.011279,-0.014655,-0.000103,-0.008896,-0.009677,-0.013941,-0.015137,-0.014748,...,-0.024337,0.014641,-0.003845,0.003503,0.014651,-0.004380,0.007626,-0.016998,0.011555,0.006891
2020-01-15,0.014152,0.004285,0.011834,0.030493,0.014774,0.018429,0.009302,0.022774,0.011832,0.021260,...,0.037349,0.020001,0.017914,-0.005539,0.013621,-0.001281,0.001498,0.012347,0.014378,0.011808
2020-01-22,-0.001024,-0.005867,-0.003119,-0.009940,-0.006159,-0.006030,-0.005144,-0.011432,-0.004331,-0.012226,...,0.011877,-0.004840,-0.001363,0.012021,0.008256,0.008264,0.013321,0.005459,0.021133,0.000855
2020-01-29,-0.025156,-0.037023,-0.025472,-0.025538,-0.030661,-0.025789,-0.025155,-0.033796,-0.034058,-0.033393,...,-0.007665,-0.002347,-0.016915,-0.012174,-0.011195,-0.026750,-0.027300,-0.001800,-0.013955,-0.003493
2020-02-05,-0.013463,-0.017243,-0.027886,-0.027554,-0.018416,-0.021319,-0.015536,-0.004595,-0.024824,0.000153,...,0.036171,0.002976,-0.001871,0.042309,0.005917,0.026576,0.035774,0.025013,0.020456,0.013409
2020-02-12,0.007005,0.012427,0.005778,-0.001065,-0.002069,0.006196,0.006246,0.009679,0.012227,0.008206,...,-0.007427,0.018419,0.018823,0.029300,0.012471,0.003676,0.018805,-0.004460,0.004072,0.004458
2020-02-19,-0.001913,0.002473,0.000594,0.005084,-0.002934,-0.005834,-0.000424,-0.002320,0.001541,0.001236,...,-0.007356,-0.001239,-0.000223,0.006086,0.003882,0.002414,0.001185,0.004195,0.006687,0.000251
2020-02-26,-0.050242,-0.032802,-0.034123,-0.050149,-0.052902,-0.044124,-0.037450,-0.055419,-0.047629,-0.053664,...,-0.062118,-0.113001,-0.076956,-0.066434,-0.077914,-0.100983,-0.098873,-0.104267,-0.079872,-0.067696
2020-03-04,-0.031142,-0.020202,-0.015973,-0.029068,-0.031891,-0.023037,-0.020310,-0.036199,-0.035800,-0.036036,...,0.014655,-0.025470,-0.016271,0.004572,-0.022725,-0.030346,0.030677,0.008318,-0.021646,0.007164
2020-03-11,-0.070591,-0.057394,-0.047208,-0.061830,-0.064298,-0.066740,-0.067643,-0.074741,-0.064195,-0.090611,...,-0.143066,-0.152154,-0.133275,-0.077682,-0.137434,-0.183704,-0.121588,-0.186849,-0.158649,-0.123318
2020-03-18,-0.152763,-0.136244,-0.132490,-0.145941,-0.169908,-0.140853,-0.174494,-0.180162,-0.186557,-0.212800,...,-0.074905,-0.178699,-0.183820,-0.070213,-0.269946,-0.158515,-0.210512,-0.301729,-0.154739,-0.146774
2020-03-25,-0.016623,-0.014282,-0.032996,-0.023734,-0.042720,-0.013870,-0.042943,-0.053595,-0.036846,-0.025050,...,-0.039094,0.164478,0.057882,0.017298,0.233247,0.077655,0.078933,0.080806,0.076751,0.057127
2020-04-01,0.045982,0.026867,-0.018974,0.027442,0.051279,0.025117,0.047044,0.069580,0.071776,0.072549,...,0.102924,0.004276,0.048600,0.032145,-0.016528,-0.003598,0.055520,0.022460,0.038694,0.021619

**Change the weekly returns from USD to EUR.**

Downloaded the dataset from here: https://www.investing.com/currencies/eur-usd

In [25]:
df_USDEUR=pd.read_csv("/Users/a/Dropbox/Thesis/Thesis/Coding/186IndexesData+Cleaning/NewDataIndexes/USD_EUR Historical Data_NEWNEW.csv", index_col=0)

In [26]:
df_USDEUR.head()

               Price    Open    High     Low Change %
Date
May 06, 2020  0.9262  0.9226  0.9266  0.9222    0.36%
May 05, 2020  0.9228  0.9168  0.9237  0.9152    0.66%
May 04, 2020  0.9168  0.9107  0.9179  0.9107    0.67%
May 01, 2020  0.9107  0.9128  0.9146  0.9075   -0.22%
Apr 30, 2020  0.9126  0.9198  0.9232  0.9114   -0.75%

Change the index to datetime

In [27]:
df_USDEUR.index.dtype

dtype('O')

In [28]:
df_USDEUR.index = pd.to_datetime(df_USDEUR.index)

In [29]:
df_USDEUR = df_USDEUR.sort_index()

The Change % column is an object, we need to change that to int and add two zeros in front of each number.

In [30]:
df_USDEUR["Change %"]=df_USDEUR["Change %"].str.split('%').str[0].tolist()

In [31]:
df_USDEUR["Change %"]=df_USDEUR["Change %"].astype("float64")

In [32]:
df_USDEUR["Change %"] = df_USDEUR["Change %"]*0.01

In [33]:
df_USDEUR.tail(10)

             Price    Open    High     Low  Change %
Date
2020-04-23  0.9278  0.9239  0.9298  0.9219    0.0042
2020-04-24  0.9240  0.9278  0.9323  0.9233   -0.0040
2020-04-27  0.9233  0.9252  0.9252  0.9206   -0.0008
2020-04-28  0.9242  0.9234  0.9251  0.9183    0.0009
2020-04-29  0.9196  0.9243  0.9244  0.9186   -0.0050
2020-04-30  0.9126  0.9198  0.9232  0.9114   -0.0075
2020-05-01  0.9107  0.9128  0.9146  0.9075   -0.0022
2020-05-04  0.9168  0.9107  0.9179  0.9107    0.0067
2020-05-05  0.9228  0.9168  0.9237  0.9152    0.0066
2020-05-06  0.9262  0.9226  0.9266  0.9222    0.0036

Calculate the cumulative weekly return on USDEUR

In [34]:
df_USDEUR_weekly = df_USDEUR["Change %"].resample("W-WED").agg(lambda x: (x+1).prod()-1)

In [35]:
df_USDEUR_weekly

Date
2013-04-10   -0.006096
2013-04-17    0.002778
2013-04-24    0.001185
2013-05-01   -0.012254
2013-05-08    0.001937
                ...
2020-04-08    0.009844
2020-04-15   -0.004752
2020-04-22    0.007998
2020-04-29   -0.004719
2020-05-06    0.007144
Freq: W-WED, Name: Change %, Length: 370, dtype: float64

Join the dataframes together

In [36]:
df_174_weekly=df_174_weekly.join(df_USDEUR_weekly)

We want the start the dataframe from the first date of the USDEUR return series, or from the 2000-11-15

In [37]:
startdate = "2000-11-14" 

df_174_weekly = df_174_weekly[df_174_weekly.index > startdate]

df_174_weekly.head()

,AsiaSMALL LoBO,AsiaME1 BO2,AsiaME1 BO3,AsiaME1 BO4,AsiaSMALL HiBO,AsiaME2 BO1,AsiaME2 BO2,AsiaME2 BO3,AsiaME2 BO4,AsiaME2 BO5,...,Trans,Whlsl,Rtail,Meals,Banks,Insur,RlEst,Fin,Other,Change %
2000-11-15,-0.019490,0.000865,-0.023041,-0.017704,-0.020493,-0.015421,-0.027340,-0.019657,-0.018711,-0.015699,...,0.026467,-0.022703,-0.026517,0.044867,-0.040242,0.011808,0.010578,-0.045932,-0.037754,NaN
2000-11-22,-0.008836,0.001184,0.000739,-0.009449,-0.012035,-0.022265,-0.007931,-0.008830,-0.007185,-0.012814,...,-0.011646,-0.038456,-0.042058,0.019162,-0.049095,-0.052143,-0.004117,-0.103085,-0.072756,NaN
2000-11-29,-0.013819,-0.009100,-0.001578,-0.015716,-0.009076,-0.036400,-0.005322,0.010489,-0.006858,-0.011438,...,0.004345,-0.008643,0.058508,-0.011066,0.061032,0.035920,0.014078,0.011448,0.022513,NaN
2000-12-06,0.026910,0.023548,0.015245,0.034176,0.029014,0.017487,0.016114,0.026030,0.062193,0.027583,...,-0.003381,-0.000192,0.014195,-0.056539,0.010007,0.048137,-0.012322,0.041712,0.068306,NaN
2000-12-13,-0.015648,-0.001104,0.003339,-0.018666,-0.003415,-0.005514,0.009608,-0.002222,0.003946,-0.002430,...,0.002377,0.005214,-0.022599,0.025697,0.038537,-0.005833,0.016457,0.050005,-0.010554,NaN

Check if we have many NaNs in the dataframe

In [38]:
df_174_weekly.isnull().sum().sum()

647

Nope perfect! No Nans in the dataframe.

And finally we want to calculate the EUR returns for the indexes.

In [39]:
for i in range(0, df_174_weekly.shape[1]-1):
    df_174_weekly.iloc[:,i]=(df_174_weekly.iloc[:,i]+1)*(df_174_weekly["Change %"]+1)-1

In [40]:
df_174_weekly.shape

(1012, 175)

In [41]:
df_174_weekly

,AsiaSMALL LoBO,AsiaME1 BO2,AsiaME1 BO3,AsiaME1 BO4,AsiaSMALL HiBO,AsiaME2 BO1,AsiaME2 BO2,AsiaME2 BO3,AsiaME2 BO4,AsiaME2 BO5,...,Trans,Whlsl,Rtail,Meals,Banks,Insur,RlEst,Fin,Other,Change %
2000-11-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2000-11-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2000-11-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2000-12-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2000-12-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-03-04,-0.053475,-0.042787,-0.038655,-0.051449,-0.054206,-0.045557,-0.042892,-0.058415,-0.058025,-0.058256,...,-0.047934,-0.038947,-0.018584,-0.045251,-0.052697,0.006919,-0.014924,-0.044198,-0.016052,-0.023051
2020-03-11,-0.081554,-0.068513,-0.058447,-0.072896,-0.075335,-0.077749,-0.078641,-0.085655,-0.075233,-0.101338,...,-0.162154,-0.143499,-0.088561,-0.147608,-0.193333,-0.131949,-0.196440,-0.168573,-0.133659,-0.011796
2020-03-18,-0.127512,-0.110500,-0.106634,-0.120486,-0.145167,-0.115246,-0.149890,-0.155727,-0.162313,-0.189338,...,-0.154221,-0.159494,-0.042501,-0.248187,-0.133435,-0.186982,-0.280917,-0.129547,-0.121344,0.029805
2020-03-25,-0.011032,-0.008677,-0.027498,-0.018184,-0.037277,-0.008263,-0.037502,-0.048214,-0.031370,-0.019506,...,0.171099,0.063897,0.023082,0.240259,0.083782,0.085067,0.086951,0.082873,0.063138,0.005686
2020-04-01,0.038170,0.019197,-0.026301,0.019768,0.043427,0.017460,0.039224,0.061591,0.063771,0.064538,...,-0.003225,0.040769,0.024436,-0.023873,-0.011041,0.047636,0.014823,0.030936,0.013988,-0.007469

**Drop the change % column from the dataframe.**

In [42]:
df_174_weekly=df_174_weekly.drop(columns=["Change %"])

**Import the bonds that we want to add to the dataframe.**

In [43]:
df_Bonds=pd.read_csv("/Users/a/Dropbox/Thesis/Thesis/Coding/186IndexesData+Cleaning/NewDataIndexes/EUROBONDS-Index.csv", index_col=0)

Here we have 6 bonds with weekly prices that shift on Mondays.

**Change the index to datetime object.**

In [44]:
df_Bonds.index=pd.to_datetime(df_Bonds.index, dayfirst=True)

**Calculate weekly returns.**

In [45]:
df_Bonds = df_Bonds/df_Bonds.shift(1)-1

In [46]:
df_Bonds

,LEATTREU Index,LET1TREU Index,LET3TREU Index,LET5TREU Index,LET7TREU Index,LET0TREU Index
1998-07-03,NaN,NaN,NaN,NaN,NaN,NaN
1998-07-31,0.012846,0.009407,0.011191,0.012776,0.014716,0.019090
1998-08-07,0.004964,0.002578,0.003801,0.004293,0.006176,0.010303
1998-08-14,0.003740,0.001187,0.003442,0.004879,0.005236,0.004827
1998-08-21,0.008063,0.002765,0.006684,0.007924,0.011332,0.014922
...,...,...,...,...,...,...
2019-03-15,-0.000839,-0.000167,-0.000460,-0.000675,-0.000740,-0.001616
2019-03-22,0.008319,0.000222,0.001439,0.003326,0.007220,0.020606
2019-03-29,0.000740,0.000222,0.000839,0.001018,0.000942,0.000760
2019-04-05,-0.002148,-0.000666,-0.001088,-0.001379,-0.002429,-0.003900
2019-04-12,-0.000404,0.000333,0.000638,0.000984,0.000106,-0.002371

**Since the other indexes shift on Wednesdays we move the weekly returns for the bonds front two days.**

In [47]:
df_Bonds = df_Bonds.shift(-2,freq="D")

**Check if there are any missing values in the dataframe.**

In [48]:
df_Bonds.isnull().sum().sum()

6

These are the 6 NaN values in the first row.

In [49]:
startdate = "2000-11-14" 

df_Bonds = df_Bonds[df_Bonds.index > startdate]

df_Bonds.head()

,LEATTREU Index,LET1TREU Index,LET3TREU Index,LET5TREU Index,LET7TREU Index,LET0TREU Index
2000-11-15,0.003267,0.001545,0.002784,0.003694,0.004148,0.005609
2000-11-22,0.003461,0.000998,0.001474,0.002552,0.004613,0.010358
2000-11-29,0.006869,0.003444,0.006166,0.007838,0.009037,0.010558
2000-12-06,0.002910,0.003071,0.004431,0.004902,0.004051,-0.002972
2000-12-13,0.006227,0.002431,0.004328,0.006113,0.007530,0.014818

**And now we can join the dataframes together into one.**

In [50]:
df_180_weekly = df_174_weekly.join(df_Bonds)

In [51]:
df_180_weekly

,AsiaSMALL LoBO,AsiaME1 BO2,AsiaME1 BO3,AsiaME1 BO4,AsiaSMALL HiBO,AsiaME2 BO1,AsiaME2 BO2,AsiaME2 BO3,AsiaME2 BO4,AsiaME2 BO5,...,Insur,RlEst,Fin,Other,LEATTREU Index,LET1TREU Index,LET3TREU Index,LET5TREU Index,LET7TREU Index,LET0TREU Index
2000-11-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.003267,0.001545,0.002784,0.003694,0.004148,0.005609
2000-11-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.003461,0.000998,0.001474,0.002552,0.004613,0.010358
2000-11-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.006869,0.003444,0.006166,0.007838,0.009037,0.010558
2000-12-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.002910,0.003071,0.004431,0.004902,0.004051,-0.002972
2000-12-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.006227,0.002431,0.004328,0.006113,0.007530,0.014818
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-03-04,-0.053475,-0.042787,-0.038655,-0.051449,-0.054206,-0.045557,-0.042892,-0.058415,-0.058025,-0.058256,...,0.006919,-0.014924,-0.044198,-0.016052,NaN,NaN,NaN,NaN,NaN,NaN
2020-03-11,-0.081554,-0.068513,-0.058447,-0.072896,-0.075335,-0.077749,-0.078641,-0.085655,-0.075233,-0.101338,...,-0.131949,-0.196440,-0.168573,-0.133659,NaN,NaN,NaN,NaN,NaN,NaN
2020-03-18,-0.127512,-0.110500,-0.106634,-0.120486,-0.145167,-0.115246,-0.149890,-0.155727,-0.162313,-0.189338,...,-0.186982,-0.280917,-0.129547,-0.121344,NaN,NaN,NaN,NaN,NaN,NaN
2020-03-25,-0.011032,-0.008677,-0.027498,-0.018184,-0.037277,-0.008263,-0.037502,-0.048214,-0.031370,-0.019506,...,0.085067,0.086951,0.082873,0.063138,NaN,NaN,NaN,NaN,NaN,NaN
2020-04-01,0.038170,0.019197,-0.026301,0.019768,0.043427,0.017460,0.039224,0.061591,0.063771,0.064538,...,0.047636,0.014823,0.030936,0.013988,NaN,NaN,NaN,NaN,NaN,NaN

In [54]:
startdate = "2013-11-14" 

df_180_weekly = df_180_weekly[df_180_weekly.index > startdate]

df_180_weekly.head()

,AsiaSMALL LoBO,AsiaME1 BO2,AsiaME1 BO3,AsiaME1 BO4,AsiaSMALL HiBO,AsiaME2 BO1,AsiaME2 BO2,AsiaME2 BO3,AsiaME2 BO4,AsiaME2 BO5,...,Insur,RlEst,Fin,Other,LEATTREU Index,LET1TREU Index,LET3TREU Index,LET5TREU Index,LET7TREU Index,LET0TREU Index
2013-11-20,0.008958,0.010674,0.006974,0.006130,0.021649,0.005035,0.029283,-0.001502,-0.002688,0.007838,...,0.012978,0.013588,0.014134,0.000721,0.000255,0.000114,0.000416,0.000807,-0.000675,0.000596
2013-11-27,-0.024176,-0.017898,-0.015373,-0.035863,-0.024114,-0.027038,-0.014162,-0.027674,-0.035042,-0.038529,...,0.014366,0.042815,0.013392,-0.003319,0.002155,0.000398,0.000580,0.001456,0.003252,0.004738
2013-12-04,-0.006209,0.023451,-0.003439,-0.010837,-0.010588,-0.005128,0.039530,-0.001245,-0.007628,-0.037184,...,-0.014749,-0.003130,-0.012510,-0.009303,-0.005663,-0.001704,-0.004075,-0.006081,-0.008496,-0.008420
2013-12-11,-0.012165,-0.023670,-0.022509,-0.020266,-0.021941,-0.016033,-0.029136,-0.014855,-0.015754,-0.014654,...,-0.020950,-0.018947,-0.021841,-0.021065,0.002710,0.000398,0.001061,0.002087,0.003003,0.006452
2013-12-18,-0.005637,-0.002575,0.002844,-0.004460,-0.020650,0.013427,0.004084,-0.004898,0.012745,-0.014383,...,0.018238,0.047257,0.050895,0.026891,-0.000936,0.000114,-0.000591,-0.001249,-0.001675,-0.001480

**Save the dataframe to a csv file.**

In [55]:
df_180_weekly.to_csv("/Users/a/Dropbox/Thesis/Thesis/Coding/PreprocessedData/out-index_data_NEWERdates.csv")